### ISSUE TITLE
wrong import

### ISSUE THREAD

**Issue by CleberRossi** [devfullcycle/fc-ddd-patterns#11]
https://github.com/devfullcycle/fc-ddd-patterns/blob/4e6ca7fa2cbbdca92260600240ff6fa0f70c11d8/src/domain/checkout/factory/order.factory.spec.ts#L1C26-L1C26

**Comment by LucianTavares** [comment]
Olá Cleber.

Obrigado por avisar sobre o import errado.
Já vou corrigir aqui.

Abraço.
